name: Code coverage report

on:
  pull_request:
  push:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      with:
        persist-credentials: false

    - name: Setup Micromamba
      uses: mamba-org/setup-micromamba@0dea6379afdaffa5d528b3d1dabc45da37f443fc # v2.0.4
      with:
        environment-name: TEST
        init-shell: bash
        create-args: >-
          python=3 pip
          --file requirements.txt
          --file test_requirements.txt
          --channel conda-forge

    - name: Install compliance-checker
      shell: bash -l {0}
      run: |
        python -m pip install -e . --no-deps --force-reinstall

    - name: Run tests with coverage
      shell: bash -l {0}
      run: |
        python -m pytest --cov=compliance_checker --cov-report=xml compliance_checker/tests
      # pass this step even if there are individual test failures, we are
      # interested in the overall level of coverage and other checks can
      # report on test failures.
      continue-on-error: true

    - name: Upload to codecov
      uses: codecov/codecov-action@ad3126e916f78f00edff4ed0317cf185271ccc2d  # v5.4.2
      with:
        files: coverage.xml
    permissions:
      actions: read
